### ISSUE TITLE
Vocabularies Management

### ISSUE THREAD

**Issue by jcaraballo17** [UCHIC/ODM2Sensor#124]
Need to add a 'New' and 'Edit' forms for the Site Type and the Equipment Type vocabularies.
- [ ] Add new Site Type
- [ ] Edit Site Type
- [ ] Add new Equipment Type
- [ ] Edit Equipment Type

**Comment by jcaraballo17** [comment]
These work the same way as the other vocabularies, and there's a couple of examples in the code. @ZachYoshikawa can take care of this.

**Comment by ZachYoshikawa** [comment]
@jcaraballo17 I am looking at the Vocabularies and see there is already 'New' and 'Edit' forms for Site Type and Equipment Type. They are functional. Am I missing something?

**Comment by AmberSJones** [comment]
Maybe this shouldn't be implemented as functionality on the Equipment Management site since these vocabularies should come from the ODM2 vocabularies site. @horsburgh , do you agree?

**Comment by horsburgh** [comment]
@jcaraballo17 and @ZachYoshikawa - @AmberSJones is right, we now have a functioning system for the ODM2 CVs at http://vocabulary.odm2.org.  So creation of any new vocabulary terms should happen there and then be retrieved into the equipment management database from that system.

**Comment by jcaraballo17** [comment]
So should we get rid of all the Controlled Vocabularies forms that are already implemented? Right now, from the odm2sensor page, we can add and edit:
Spatial Offset Type
Site Type
Sampling Feature Type
Equipment Type
Action Type
Method Type
Organization Type

**Comment by horsburgh** [comment]
@jcaraballo17 - These are all covered at http://vocabulary.odm2.org.  So, that's where you should get the terms to keep an ODM2 database up to date, but any additions/editing should be done at http://vocabulary.odm2.org.

**Comment by AmberSJones** [comment]
So, the resolution on this issue is that these all of these Types should not be edit-able on the odm2sensor/equipment management system.

**Comment by ZachYoshikawa** [comment]
@AmberSJones Will you be able to add to or edit the tables without the new, edit, and delete functionality on the django website?

**Comment by AmberSJones** [comment]
Vocabularies will be edited via the controls on the http://vocabulary.odm2.org page and then the vocabularies on the database underlying our odm2sensor web application will be synced via a script that @sreeder developed or manually.

**Comment by ZachYoshikawa** [comment]
Perfect. I pushed the changes. Hence, "ready for testing". I want to include the jQuery dataTable for the tables that don't have a Search bar or Show "50" entries. If I can't figure it out I will ask @jcaraballo17 about it.

**Comment by ZachYoshikawa** [comment]
@AmberSJones I noticed that creating or editing an "Organization" from the Vocabularies tab leads to a form page for creating and deleting a "Vendor". Why do both terms exist?

**Comment by AmberSJones** [comment]
Great on the 'Types' vocabularies. I think we should consider a re-organization of the 'Vocabularies' pages so that the edit-able tables are better grouped together. I will add that as a new issue.

Regarding Organization and Vendor, a vendor is a type of organization. A previous schema used 'Vendor', so some of the forms still have this terminology- we should correct.

I'm going to close this issue and add those as new ones.
